name: Icon request (app / site)
description: Suggest a new icon.
title: "Icon request: "
labels: ["New Icon"]
body:
  - type: markdown
    attributes:
      value: |
        ### :loudspeaker: [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already!
        :angry: **If you don't read / follow the issue guidelines**, your issue(s) might **get rejected** and, *in the worse case*, **get you banned.**
        *(Issue guidelines was last updated on: **2022-10-26**).*
        
        *And do not request multiple icons in single issue, make multiple issues instead.*
        
        ### :triangular_flag_on_post: Issue title formatting *(top text field)*
        - Remember to **add name of the brand / site / app** at the end of *"Icon request:"* text.
          - Eg. `Icon request: GitHub`
        - Please use proper capitalization / spelling for the name (check the capitalization / spelling from browser tab title or body text of their website, **not from the logo!**).
        - **Do not change the formatting of the title!**
        
        ---
  - type: input
    id: site_app-url
    attributes:
      label: URL for the brand / site / app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to add *https://* (or *http://*) to start of the URL.
        Link should be the homepage of the site (not login page or any other miscellaneous page).
        
        - :globe_with_meridians: Please link to english version of the site, if site has that option!
        - :underage: If this entity is explicitly ["not safe for work"](https://en.wikipedia.org/wiki/Not_safe_for_work), please add ` (NSFW)` after the URL.
        - :warning: **Don't add Play Store link or other app store links**, unless requested entity doesn't have any other website.
        
        ---
  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
  - type: markdown
    attributes:
      value: |
        Optional option to add URL for *press kit* or *logo SVG / EPS / AI vector resource*, preferably from official source ([tips for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images)).
        
        - :x: **Unaccepted resources:** JPG, PNG, GIF, WebP, ICO or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats_(2D)).
          - *[Why vector images instead of raster (a.k.a. bitmap) images](https://www.lifewire.com/vector-and-bitmap-images-1701238#toc-ease-of-use-vectors-are-more-robust)*.
        - :x: **NO [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme), SVG code** or anything **that's NOT web URL!** *(Forbidden because of long character lengths.)*
          - Data uri starts with: `data:image/` (and so on)
          - SVG code starts with: `<svg` (and so on)
        
        *Adding a optional resource doesn't guarantee that aegis-icons will use it for the icon.*
        
        ---
  - type: textarea
    id: 2fa-proof
    attributes:
      label: Proof of the Aegis-compatible 2FA
  - type: markdown
    attributes:
      value: |
        *Add either:*
        - Link to documentation page / announcement post related to TOTP / Google Authenticator 2FA (**prefered option #1**)
        - Link to 2FA Directory's GitHub pull request page for the service ([search them here](https://github.com/2factorauth/twofactorauth/pulls?q=is%3Apr), **prefered option #2**)
        - Screenshot proof of the TOTP / Google Authenticator 2FA settings page or login prompt **(if either prefered option wasn't available)**
          - :x: **NO screenshots from Aegis app, period!** Only from the service you have the account on.
          - *Censor sensitive info if needed (QR codes, 2FA seed codes, personal information etc.)*
          
        > **Note** – Documentation link or screenshot should clearly mention that 2FA is (T)OTP / HOTP or any mobile 2FA app (eg. Google Authenticator, Microsoft Authenticator, LastPass Authenticator etc.) or show section of the 2FA setup page with *(censored)* OTP 2FA QR code image. **Otherwise we cannot be sure if 2FA actually is compatible for Aegis.**
        
        *This is optional, but **if we cannot find info about 2FA from the website, Google nor [2FA Directory](https://2fa.directory/int/)**, then we **reject the request** (we give you possibility for reopening though by sending the proof via comment).*
        
        ---
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: "Optional text field to add other info: extra info about branding, kudos etc."
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.
          required: true