name: Icon request (app / site)
description: Suggest a new icon.
title: "Icon request: "
labels: ["New Icon"]
body:
  - type: markdown
    attributes:
      value: |
        - тЪа Remember to **add name of the site or app** at the end of *"Icon request:"* part on top, **do not change the formatting of the title!**
          - Please use proper capitalization for the name (check the capitalization from their app / website).
        
        [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already (only takes half a minute to read!)
  - type: input
    id: site_app-url
    attributes:
      label: URL of the site or app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        тод Remember to add *https://* (or *http://*) to start of the URL.
  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/logo.svg OR https://example.com/press-kit
  - type: markdown
    attributes:
      value: |
        тод **Optional** option to add URL for *logo SVG vector* or *press kit*, **no JPG / PNG / GIF files!** ([Tips for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-source-images))
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.