name: Icon request (generic)
description: Suggest a new *generic* icon (i.e. icon that doesn't represent any brand and uses symbols).
title: "Generic icon request: "
labels: ["New Icon", "Generic"]
body:
  - type: markdown
    attributes:
      value: |
        ### :loudspeaker: [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already!
        :angry: **If you don't read / follow the issue guidelines**, your issue(s) might **get rejected** and, *in the worse case*, **get you banned.**
        *(Issue guidelines was last updated on: **2022-08-18**).*
        
        *And do not request multiple icons in single issue, make multiple issues instead.*
        
        ### :triangular_flag_on_post: Issue title formatting *(top text field)*
        - Remember to **add symbol name** at the end of *"Generic icon request:"* text.
          - Eg. `Generic icon request: Education`
        - Do not change the formatting of the title!
        
        If you can't think of **symbol name**, use these sites as reference:
        - https://iconscout.com/unicons/explore/line
        - https://feathericons.com/
        - https://lucide.dev/
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.
          required: true