name: Update icon
description: Request update for icon, if branding is outdated or brand changed their name.
title: "Update icon: "
labels: ["Update"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### :loudspeaker: [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already! _Always recheck them for any guideline updates._
        > 
        > ### :scroll: Please fill out this issue form following the instructions.
        >
        > - :warning: **If you don't read / follow the issue guidelines and fill out this issue form as instructed**, your issue(s) might **get rejected** and, _in the worse case_, **get you banned indefinitely.**
        > - :x: Do not request multiple icons in single issue, make multiple issues instead.
        >
        > ### :triangular_flag_on_post: Issue title formatting _(text field at the top)_
        > - Remember to **add name of the brand / site / app** at the end of _"Update icon:"_ text.
        >   - Example: `Update icon: GitHub`
        >   - If brand changed their name, format it like this: `Update icon: NEW-BRAND-NAME (f.k.a. OLD-BRAND-NAME)`
        > - Please use proper capitalization / spelling for the name.
        >   - Check the capitalization / spelling from browser tab title or body text of their website, **not from the logo!**
        > - **Do not change the formatting of the title!**
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: markdown
    attributes:
      value: <a name="url-requirements"></a>
      
  - type: input
    id: site_app-url
    attributes:
      label: URL for the brand / site / app
      description: |
        1. **Remember to add _https://_ (or _http://_)** to start of the URL.
        2. **Link should be the homepage of the site** (not login page or any other miscellaneous page).
      placeholder: Eg. https://example.com
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        - Please link to english version of the site, if site has that option!
        - If site is explicitly ["not safe for work"](https://en.wikipedia.org/wiki/Not_safe_for_work), please add ` (NSFW)` after the URL.
        - :x: **NO Play Store links or other app store links**, unless requested entity doesn't have any other website.
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: dropdown
    id: update-reason
    attributes:
      label: Reason for update
      description: |
        **Please write explanation on the "Anything else?" section** if you selected either `Brand overhaul (a corporate name change)` or `Other`.
      options:
        - Redesigned logo or brand update
        - Brand overhaul (a corporate name change)
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
      description: |
        Optional. Add URL for **press kit** or _logo SVG / EPS / AI vector resource_, preferably from official source ([instructions for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-the-source-material)).

  - type: markdown
    attributes:
      value: |
        - :x: **Unaccepted resources:** JPG, PNG, GIF, WebP, AVIF, ICO or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats_(2D)).
          - Please leave it empty if you **haven't found** vector resources. Raster resources aren't helpful.
        - :x: **NO [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme), SVG code** or anything **that's NOT web URL!**
          - _Forbidden because of long character lengths._
          - Data URI starts with: `data:image/` (and so forth).
          - SVG code starts with: `<svg` (and so forth).
          
        _Adding resource doesn't guarantee that aegis-icons will use it for the icon._
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->
        


  - type: markdown
    attributes:
      value: <a name="explanation"></a>
      
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: "Optional text field to add other info: more info about reason to update, extra info about branding, kudos etc."
  - type: markdown
    attributes:
      value: |
        :point_up: **REQUIRED** if you selected `Brand overhaul (a corporate name change)` or `Other` as reason for update. Explain in detail, so we understand the situation (for example: what was the change, when this change approximately happen, any related news coverage links).
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: checkboxes
    id: issue-checks
    attributes:
      label: Confirmations
      description: |
        **IMPORTANT:** Please read each item carefully before confirming and answer truthfully.
      options:
        - label: I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & this issue form's instructions.
          required: true
        - label: I added the name of the brand / site / app to the issue title _(text field at the top)_.
          required: true
        - label: I used proper capitalization / spelling for the brand / site / app on the issue title _(text field at the top)_.
          required: true
        - label: I keep the formatting of the issue title intact _(text field at the top)_.
          required: true
        - label: The URL that I added meets [the requirements](#url-requirements).
          required: true
        - label: _If I selected **Brand overhaul (a corporate name change)** or **Other** as reason for update,_ then I also [wrote explanation](#explanation).
          required: true
        - label: By checking this box, I acknowledge that **I did _not_** follow the given instructions.
          required: false
