name: Icon submission
description: Submit your icon creation! Remember to read CONTRIBUTING.md first, if you haven't already.
title: "Icon submission: "
labels: ["Submission"]
body:
  - type: markdown
    attributes:
      value: |
        ### :loudspeaker: Read and carefully follow our [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)!
        :angry: **If you don't read & follow the CONTRIBUTING doc,** we might reject your icon submission(s) and, *in the worse case*, **get you banned.**
        
        *And do not send multiple icons in single issue, make multiple issues instead.*
        
        ### :triangular_flag_on_post: Issue title formatting *(top text field)*
        - Remember to add *name of the brand / site / app* at the end of *"Icon submission:"* text.
        - Please use proper capitalization / spelling for the name (check the capitalization / spelling from browser tab title or body text of their website, **not from the logo!**).
        - If it's icon update submission, add `(update)` at the end of *"Icon submission:"* text.
          - Eg. `Icon submission: Discord (update)`
        - If it's generic icon submission, add *short name for the icon* and `(generic)` at the end of *"Icon submission:"* text.
          - Eg. `Icon submission: Education (generic)`
        - **Do not change the formatting of the title!**
    validations:
      required: true
  - type: input
    id: site_app-url
    attributes:
      label: URL of the site or app
      placeholder: Eg. https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to add *https://* (or *http://*) to start of the URL.
        Link should be the homepage of the site (not login page or any other miscellaneous page).
        
        - :globe_with_meridians: Please link to english version of the site, if site has that option!
        - :underage: If this entity is explicitly ["not safe for work"](https://en.wikipedia.org/wiki/Not_safe_for_work), please add ` (NSFW)` after the URL.
        - :warning: **Don't add Play Store link or other app store links**, unless requested entity doesn't have any other website.
        
        :raising_hand: *If icon submission is generic icon, add this text instead of URL:* `Skipped, generic icon`
  - type: textarea
    id: logo-url
    attributes:
      label: Logo / icon info
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > **Note** – Only text input allowed for this text area, **don't embed images or other files.** Thanks!
        
        **For example:**
        
        - Direct URL of the press kit / branding page *(most prefered)*, logo vector file or [logo resource page](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#logos)
          - Examples:
            - `https://official-domain-of-the-app-or-site.com/press-kit-slash-branding-page`
            - `https://official-domain-of-the-app-or-site.com/logo.svg`
            - `https://unofficial-vector-logo-resource.com/exact-page-with-logo-resource`
        - Short info of how did you get the logo
          - For site embedded vectors, eg: `Extracted logo with SVG Gobbler from https://official-domain-of-the-app-or-site.com/exact-page`
          - For [image traced vectors](https://en.wikipedia.org/wiki/Image_tracing), eg: `Image traced of https://example.com/logo.jpg with Vectorizer.io`
        - *If it's generic icon:*
          - `[Icon name] from Unicons / Feather / Lucide / Cryptocurrency Icons`
        
        :warning: **It cannot be just duplication of** "URL of the site or app" **field text.**
  - type: textarea
    id: bg-color
    attributes:
      label: Background color info
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Fill this form based of this information:
        - *Is the color taken somewhere from the logo?*
          - If **yes**, add & edit this text for eg: ``Background color is from the logo (`#add-hex-color-code-here`).``
        - *Is color taken from the mentioned app / site?* (And not from logo)
          - If **yes**, do either/all of these things:
            - [Upload](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files) screenshot of the area where you got the color **and** give URL of the page
            - Give the HTML element name (eg. `#footer`) **and** URL of the page.
            
        :raising_hand: *If icon submission is generic icon, add this text instead of URL:* `Skipped, generic icon`
  - type: textarea
    id: icon-upload
    attributes:
      label: Upload icon(s)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |        
        First, click the text field above and then [upload](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files) **SVGs inside of ZIP file** (even though SVG to Markdown upload is now possible, [there's still some issues with it](https://github.com/github/feedback/discussions/11053)).
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.
          required: true