name: Other
description: For anything else, DO NOT USE THIS FOR ICON REQUESTS OR SUBMISSIONS!
labels: ["Other"]
body:
  - type: markdown
    attributes:
      value: |
        Add short and understandable title to the top text field.
        
        :loudspeaker: Follow the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) *(when needed)* and [Code of Conduct](https://github.com/aegis-icons/aegis-icons/blob/master/CODE-OF-CONDUCT.md).
        
        :warning: **Do not use this form for icon requesting or submissions!** Any icon requests / submissions using this form are rejected.
        
        ---
  - type: textarea
    id: issue
    attributes:
      label: Issue
    validations:
      required: true