blank_issues_enabled: false
contact_links:
  - name: Issues closed temporarily
    url: https://github.com/aegis-icons/aegis-icons/issues/931
    about: More info at the link, bypassing this and creating empty issue = instant delete & ban.